// GENERATED by scripts/gen-catalog-index.mjs from js/courses-data.js — do not edit by hand.
// 14 courses. Re-run the script after changing the built-in catalog.
export const CATALOG = {
  "fractions-made-fun": {
    "title": "Fractions Made Fun",
    "category": "mathematics",
    "lessons": [
      "fractions-made-fun::1",
      "fractions-made-fun::2",
      "fractions-made-fun::3",
      "fractions-made-fun::4",
      "fractions-made-fun::5",
      "fractions-made-fun::6",
      "fractions-made-fun::7",
      "fractions-made-fun::8",
      "fractions-made-fun::9",
      "fractions-made-fun::10",
      "fractions-made-fun::11",
      "fractions-made-fun::12",
      "fractions-made-fun::13",
      "fractions-made-fun::14",
      "fractions-made-fun::15",
      "fractions-made-fun::16"
    ]
  },
  "multiplication-mastery": {
    "title": "Multiplication Mastery",
    "category": "mathematics",
    "lessons": [
      "multiplication-mastery::1",
      "multiplication-mastery::2",
      "multiplication-mastery::3",
      "multiplication-mastery::4",
      "multiplication-mastery::5",
      "multiplication-mastery::6",
      "multiplication-mastery::7"
    ]
  },
  "english-reading-starter": {
    "title": "English Reading Starter",
    "category": "languages",
    "lessons": [
      "english-reading-starter::1",
      "english-reading-starter::2",
      "english-reading-starter::3",
      "english-reading-starter::4",
      "english-reading-starter::5",
      "english-reading-starter::6",
      "english-reading-starter::7"
    ]
  },
  "creative-writing-for-kids": {
    "title": "Creative Writing for Kids",
    "category": "languages",
    "lessons": [
      "creative-writing-for-kids::1",
      "creative-writing-for-kids::2",
      "creative-writing-for-kids::3",
      "creative-writing-for-kids::4",
      "creative-writing-for-kids::5",
      "creative-writing-for-kids::6",
      "creative-writing-for-kids::7",
      "creative-writing-for-kids::8"
    ]
  },
  "kiswahili-kwa-watoto": {
    "title": "Kiswahili kwa Watoto",
    "category": "languages",
    "lessons": [
      "kiswahili-kwa-watoto::1",
      "kiswahili-kwa-watoto::2",
      "kiswahili-kwa-watoto::3",
      "kiswahili-kwa-watoto::4",
      "kiswahili-kwa-watoto::5",
      "kiswahili-kwa-watoto::6",
      "kiswahili-kwa-watoto::7"
    ]
  },
  "science-explorers-human-body": {
    "title": "Science Explorers: The Human Body",
    "category": "science",
    "lessons": [
      "science-explorers-human-body::1",
      "science-explorers-human-body::2",
      "science-explorers-human-body::3",
      "science-explorers-human-body::4",
      "science-explorers-human-body::5",
      "science-explorers-human-body::6",
      "science-explorers-human-body::7"
    ]
  },
  "plants-and-our-environment": {
    "title": "Plants and Our Environment",
    "category": "science",
    "lessons": [
      "plants-and-our-environment::1",
      "plants-and-our-environment::2",
      "plants-and-our-environment::3",
      "plants-and-our-environment::4",
      "plants-and-our-environment::5",
      "plants-and-our-environment::6"
    ]
  },
  "coding-for-beginners-scratch": {
    "title": "Coding for Beginners with Scratch",
    "category": "computer-studies",
    "lessons": [
      "coding-for-beginners-scratch::1",
      "coding-for-beginners-scratch::2",
      "coding-for-beginners-scratch::3",
      "coding-for-beginners-scratch::4",
      "coding-for-beginners-scratch::5",
      "coding-for-beginners-scratch::6",
      "coding-for-beginners-scratch::7",
      "coding-for-beginners-scratch::8"
    ]
  },
  "web-design-basics": {
    "title": "Web Design Basics: HTML & CSS",
    "category": "computer-studies",
    "lessons": [
      "web-design-basics::1",
      "web-design-basics::2",
      "web-design-basics::3",
      "web-design-basics::4",
      "web-design-basics::5",
      "web-design-basics::6",
      "web-design-basics::7",
      "web-design-basics::8",
      "web-design-basics::9"
    ]
  },
  "digital-safety-for-students": {
    "title": "Digital Safety for Students",
    "category": "computer-studies",
    "lessons": [
      "digital-safety-for-students::1",
      "digital-safety-for-students::2",
      "digital-safety-for-students::3",
      "digital-safety-for-students::4",
      "digital-safety-for-students::5",
      "digital-safety-for-students::6"
    ]
  },
  "study-skills-and-exam-prep": {
    "title": "Study Skills & Exam Preparation",
    "category": "study-skills",
    "lessons": [
      "study-skills-and-exam-prep::1",
      "study-skills-and-exam-prep::2",
      "study-skills-and-exam-prep::3",
      "study-skills-and-exam-prep::4",
      "study-skills-and-exam-prep::5",
      "study-skills-and-exam-prep::6"
    ]
  },
  "introduction-to-ai": {
    "title": "Introduction to Artificial Intelligence",
    "category": "computer-studies",
    "lessons": [
      "introduction-to-ai::1",
      "introduction-to-ai::2",
      "introduction-to-ai::3",
      "introduction-to-ai::4",
      "introduction-to-ai::5",
      "introduction-to-ai::6",
      "introduction-to-ai::7"
    ]
  },
  "world-geography-and-cultures": {
    "title": "World Geography & Cultures",
    "category": "social-studies",
    "lessons": [
      "world-geography-and-cultures::1",
      "world-geography-and-cultures::2",
      "world-geography-and-cultures::3",
      "world-geography-and-cultures::4",
      "world-geography-and-cultures::5",
      "world-geography-and-cultures::6"
    ]
  },
  "art-music-and-creativity": {
    "title": "Art, Music & Creativity",
    "category": "creative",
    "lessons": [
      "art-music-and-creativity::1",
      "art-music-and-creativity::2",
      "art-music-and-creativity::3",
      "art-music-and-creativity::4",
      "art-music-and-creativity::5",
      "art-music-and-creativity::6"
    ]
  }
};
