/* Smart21brain AI — Study: flashcards and scored quizzes.
   Source can be a topic, pasted notes, or any AI answer ("Make flashcards" / "Quiz me on this" under each answer).
   Cards and quizzes are generated by the AI tools "flashcards" and "quizjson" (POST /api/ai-assistant), then played in the browser.
   Study sets and best scores are saved only on this device. */
(function () {
  'use strict';
  var L = window.S21AIL, T = L.t, Chat = window.S21Chat, X = window.S21X;
  if (!L || !Chat || !X) return;
  var $ = X.$, $$ = X.$$, esc = X.esc, el = X.el;

  L.extend({
    en: {
      st_title: 'Flashcards & quizzes', st_source: 'Topic or text', st_source_ph: 'e.g. Photosynthesis — or paste your notes here', st_make: 'Create', st_flash: 'Flashcards', st_quiz: 'Scored quiz',
      st_count: 'How many', st_diff: 'Difficulty', d_easy: 'Easy', d_medium: 'Medium', d_hard: 'Hard', st_generating: 'Creating your study set…', st_failed: 'I could not create that. Check your connection and try again.',
      st_bad: 'The answer could not be understood. Please try again.', st_retry: 'Try again', st_mine: 'My study sets', st_none: 'Nothing saved yet. Your flashcards and quiz results appear here.',
      st_cards: 'cards', st_questions: 'questions', st_best: 'Best', st_open: 'Open', st_delete: 'Delete', st_flip: 'Tap the card to flip', st_prev: 'Previous', st_next: 'Next',
      st_known: 'Got it', st_learning: 'Still learning', st_shuffle: 'Shuffle', st_restart: 'Start again', st_done: 'Deck finished', st_known_n: 'You know {k} of {n} cards', st_review_missed: 'Review {m} missed',
      st_score: 'Score', st_streak: 'Streak', st_correct: 'Correct!', st_wrong: 'Not quite', st_answer_is: 'Correct answer', st_finish: 'See results', st_result: 'Quiz finished',
      st_retry_mistakes: 'Retry mistakes', st_new_quiz: 'New quiz on this topic', st_back: 'Back', st_mistakes: 'Mistakes to review', st_your: 'You answered',
      st_perfect: 'Perfect score! Brilliant work.', st_good: 'Great job — keep going!', st_okay: 'Good start — review the mistakes and try again.', st_low: 'Keep practising — you will get there.',
      fc_btn: 'Make flashcards', qz_btn: 'Quiz me on this', st_question_n: 'Question {n} of {t}', st_card_n: 'Card {n} of {t}', st_short: 'Please type a topic or paste some text first.', st_all_known: 'You know every card!'
    },
    sw: {
      st_title: 'Kadi za kujifunza na majaribio', st_source: 'Mada au maandishi', st_source_ph: 'mf. Usanisinuru — au bandika maelezo yako hapa', st_make: 'Tengeneza', st_flash: 'Kadi za kujifunza', st_quiz: 'Jaribio lenye alama',
      st_count: 'Ngapi', st_diff: 'Ugumu', d_easy: 'Rahisi', d_medium: 'Wastani', d_hard: 'Gumu', st_generating: 'Natengeneza zana zako za kujifunza…', st_failed: 'Sikuweza kutengeneza hicho. Angalia mtandao wako kisha jaribu tena.',
      st_bad: 'Jibu halikueleweka. Tafadhali jaribu tena.', st_retry: 'Jaribu tena', st_mine: 'Zana zangu za kujifunza', st_none: 'Hakuna kilichohifadhiwa bado. Kadi na matokeo yako ya majaribio yataonekana hapa.',
      st_cards: 'kadi', st_questions: 'maswali', st_best: 'Bora', st_open: 'Fungua', st_delete: 'Futa', st_flip: 'Gusa kadi kuigeuza', st_prev: 'Iliyotangulia', st_next: 'Inayofuata',
      st_known: 'Nimeelewa', st_learning: 'Bado najifunza', st_shuffle: 'Changanya', st_restart: 'Anza upya', st_done: 'Kadi zimeisha', st_known_n: 'Unajua kadi {k} kati ya {n}', st_review_missed: 'Pitia {m} ulizokosa',
      st_score: 'Alama', st_streak: 'Mfululizo', st_correct: 'Sahihi!', st_wrong: 'Si kabisa', st_answer_is: 'Jibu sahihi', st_finish: 'Ona matokeo', st_result: 'Jaribio limeisha',
      st_retry_mistakes: 'Jaribu makosa tena', st_new_quiz: 'Jaribio jipya kwa mada hii', st_back: 'Rudi', st_mistakes: 'Makosa ya kupitia', st_your: 'Ulijibu',
      st_perfect: 'Alama kamili! Kazi nzuri sana.', st_good: 'Vizuri sana — endelea!', st_okay: 'Mwanzo mzuri — pitia makosa kisha ujaribu tena.', st_low: 'Endelea kujizoeza — utafika.',
      fc_btn: 'Tengeneza kadi', qz_btn: 'Nijaribu kwa hili', st_question_n: 'Swali {n} kati ya {t}', st_card_n: 'Kadi {n} kati ya {t}', st_short: 'Tafadhali andika mada au bandika maandishi kwanza.', st_all_known: 'Unajua kadi zote!'
    }
  });
  var fmt = function (k, o) { return T(k).replace(/\{(\w+)\}/g, function (_, n) { return o[n]; }); };

  /* ---------------- storage ---------------- */
  var KEY = 's21ai-study-v1', store = { decks: [] };
  try { var sv = JSON.parse(localStorage.getItem(KEY) || '{}'); if (sv && Array.isArray(sv.decks)) store.decks = sv.decks.slice(0, 30); } catch (e) {}
  function save() { try { localStorage.setItem(KEY, JSON.stringify(store)); } catch (e) { store.decks = store.decks.slice(0, 10); try { localStorage.setItem(KEY, JSON.stringify(store)); } catch (e2) {} } }
  function uid() { return 'd' + Date.now().toString(36) + Math.random().toString(36).slice(2, 5); }
  function titleOf(src) { var t = src.replace(/\s+/g, ' ').trim(); return t.length > 44 ? t.slice(0, 44).replace(/\s+\S*$/, '') + '…' : t; }

  /* ---------------- AI → items ---------------- */
  function shuffle(a) { a = a.slice(); for (var i = a.length - 1; i > 0; i--) { var j = Math.floor(Math.random() * (i + 1)), t = a[i]; a[i] = a[j]; a[j] = t; } return a; }
  function parseList(text) {
    var t = String(text || '').replace(/```(?:json)?/gi, '').trim(), a = t.indexOf('['), b = t.lastIndexOf(']');
    if (a < 0 || b <= a) throw new Error('bad');
    var arr = JSON.parse(t.slice(a, b + 1)); if (!Array.isArray(arr)) throw new Error('bad'); return arr;
  }
  function cleanCards(arr) {
    var out = arr.map(function (c) { return c && typeof c === 'object' ? { q: String(c.q || c.question || c.front || '').trim().slice(0, 300), a: String(c.a || c.answer || c.back || '').trim().slice(0, 500) } : null; }).filter(function (c) { return c && c.q && c.a; });
    if (!out.length) throw new Error('bad'); return out;
  }
  function cleanQuiz(arr) {
    var out = arr.map(function (c) {
      if (!c || typeof c !== 'object') return null;
      var opts = (Array.isArray(c.options) ? c.options : Array.isArray(c.choices) ? c.choices : []).map(function (o) { return String(o == null ? '' : o).replace(/^\s*[A-Da-d][).:]\s+/, '').trim().slice(0, 200); }).filter(Boolean).slice(0, 4);
      var ans = c.answer; if (typeof ans === 'string') { var k = 'ABCD'.indexOf(ans.trim().toUpperCase()); ans = ans.trim().length === 1 && k >= 0 ? k : opts.indexOf(ans.trim()); } ans = Number(ans);
      var q = String(c.q || c.question || '').trim().slice(0, 300);
      if (!q || opts.length < 2 || !Number.isInteger(ans) || ans < 0 || ans >= opts.length) return null;
      var correct = opts[ans], mixed = shuffle(opts); // shuffle so the right answer is not always in the same place
      return { q: q, options: mixed, answer: mixed.indexOf(correct), why: String(c.why || c.explanation || '').trim().slice(0, 400) };
    }).filter(Boolean);
    if (!out.length) throw new Error('bad'); return out;
  }
  var ctrl = null;
  function generate(type, source, count, diff) {
    if (ctrl) ctrl.abort(); ctrl = new AbortController(); var my = ctrl;
    function once() {
      return fetch('/api/ai-assistant', { method: 'POST', signal: my.signal, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ prompt: source.slice(0, 11000), context: { page: 'ai', tool: type === 'flash' ? 'flashcards' : 'quizjson', opts: { count: count, difficulty: diff }, locale: L.lang() } }) })
        .then(function (r) { return r.json().catch(function () { return {}; }).then(function (d) { if (!r.ok || !d.answer) { var e = new Error(d.error || 'net'); e.net = true; throw e; } return d.answer; }); })
        .then(function (txt) { var arr = parseList(txt); return type === 'flash' ? cleanCards(arr) : cleanQuiz(arr); });
    }
    return once().catch(function (e) { if (e.name === 'AbortError' || e.net) throw e; return once(); }); // one automatic retry if the JSON was malformed
  }

  /* ---------------- modal views ---------------- */
  var M = null;
  function open(o) {
    o = o || {}; if (M) M.close();
    M = X.modal(T('st_title'), 'fa-graduation-cap', 'x-wide x-study');
    M.onClose = function () { if (ctrl) ctrl.abort(); document.removeEventListener('keydown', keys, true); M = null; };
    document.addEventListener('keydown', keys, true);
    home(o);
    if (o.auto && o.source) run(o.type || 'flash', o.source, o.type === 'quiz' ? 8 : 10, 'medium');
  }
  var keyHandler = null;
  function keys(e) { if (keyHandler && M && !/^(textarea|input|select)$/i.test(e.target.tagName)) keyHandler(e); }

  function home(o) {
    keyHandler = null; var b = M.body, type = o.type || 'flash';
    b.innerHTML =
      '<div class="x-field"><label for="stSrc">' + esc(T('st_source')) + '</label><textarea id="stSrc" class="x-ta" rows="4" maxlength="6000" placeholder="' + esc(T('st_source_ph')) + '"></textarea></div>' +
      '<div class="st-opts"><div class="x-field"><div class="x-seg" data-seg="type"><button type="button" data-v="flash" class="' + (type === 'flash' ? 'on' : '') + '" aria-pressed="' + (type === 'flash') + '"><i class="fa-solid fa-clone"></i> ' + esc(T('st_flash')) + '</button><button type="button" data-v="quiz" class="' + (type === 'quiz' ? 'on' : '') + '" aria-pressed="' + (type === 'quiz') + '"><i class="fa-solid fa-circle-question"></i> ' + esc(T('st_quiz')) + '</button></div></div>' +
      '<div class="x-field st-count"><label class="x-rng"><span>' + esc(T('st_count')) + '</span><input type="range" id="stN" min="5" max="20" step="1" value="10"><output>10</output></label></div>' +
      '<div class="x-field st-diff"><label>' + esc(T('st_diff')) + '</label><div class="x-seg" data-seg="diff"><button type="button" data-v="easy" aria-pressed="false">' + esc(T('d_easy')) + '</button><button type="button" data-v="medium" class="on" aria-pressed="true">' + esc(T('d_medium')) + '</button><button type="button" data-v="hard" aria-pressed="false">' + esc(T('d_hard')) + '</button></div></div></div>' +
      '<div class="x-row"><button type="button" class="pill-btn primary st-go"><i class="fa-solid fa-wand-magic-sparkles"></i> ' + esc(T('st_make')) + '</button></div><p class="st-msg" role="alert" hidden></p>' +
      '<h4 class="st-h">' + esc(T('st_mine')) + '</h4><div class="st-list"></div>';
    var src = $('#stSrc', b), n = $('#stN', b), out = $('output', b), msg = $('.st-msg', b); if (o.source) src.value = o.source.slice(0, 6000);
    function sync() { var t = $('[data-seg=type] .on', b).getAttribute('data-v'); $('.st-diff', b).style.display = t === 'quiz' ? '' : 'none'; n.min = t === 'quiz' ? 5 : 5; n.max = t === 'quiz' ? 15 : 20; if (+n.value > +n.max) n.value = n.max; if (t === 'quiz' && +n.value === 10) n.value = 8; out.textContent = n.value; }
    $$('.x-seg', b).forEach(function (g) { g.addEventListener('click', function (e) { var x = e.target.closest('button'); if (!x) return; $$('button', g).forEach(function (y) { y.classList.toggle('on', y === x); y.setAttribute('aria-pressed', y === x); }); sync(); }); });
    n.addEventListener('input', function () { out.textContent = n.value; }); sync();
    $('.st-go', b).addEventListener('click', function () {
      var s = src.value.trim(); if (s.length < 3) { msg.textContent = T('st_short'); msg.hidden = false; src.focus(); return; }
      run($('[data-seg=type] .on', b).getAttribute('data-v'), s, +n.value, $('[data-seg=diff] .on', b).getAttribute('data-v'));
    });
    var list = $('.st-list', b);
    function paintList() {
      list.innerHTML = store.decks.length ? store.decks.map(function (d) {
        return '<div class="st-item" data-id="' + d.id + '"><i class="fa-solid ' + (d.type === 'flash' ? 'fa-clone' : 'fa-circle-question') + '"></i><div class="st-info"><b>' + esc(d.title) + '</b><span>' + d.items.length + ' ' + esc(T(d.type === 'flash' ? 'st_cards' : 'st_questions')) + (d.best != null ? ' · ' + esc(T('st_best')) + ' ' + d.best + '%' : '') + '</span></div><button type="button" class="pill-btn st-open">' + esc(T('st_open')) + '</button><button type="button" class="icon-btn st-del" aria-label="' + esc(T('st_delete')) + '" title="' + esc(T('st_delete')) + '"><i class="fa-regular fa-trash-can"></i></button></div>';
      }).join('') : '<p class="st-empty">' + esc(T('st_none')) + '</p>';
    }
    paintList();
    list.addEventListener('click', function (e) {
      var it = e.target.closest('.st-item'); if (!it) return; var d = store.decks.filter(function (x) { return x.id === it.getAttribute('data-id'); })[0]; if (!d) return;
      if (e.target.closest('.st-del')) { store.decks = store.decks.filter(function (x) { return x !== d; }); save(); paintList(); }
      else if (e.target.closest('.st-open')) play(d);
    });
  }

  function loading() { keyHandler = null; M.body.innerHTML = '<div class="st-load"><div class="st-spin"></div><p>' + esc(T('st_generating')) + '</p></div>'; }
  function run(type, source, count, diff) {
    loading();
    generate(type, source, count, diff).then(function (items) {
      if (!M) return; var d = { id: uid(), type: type, title: titleOf(source), source: source.slice(0, 6000), items: items, created: Date.now(), best: null, diff: diff, count: count };
      store.decks.unshift(d); store.decks = store.decks.slice(0, 30); save(); play(d);
    }).catch(function (e) {
      if (!M || (e && e.name === 'AbortError')) return;
      M.body.innerHTML = '<div class="st-load"><i class="fa-solid fa-triangle-exclamation st-warn"></i><p>' + esc(e && e.net ? T('st_failed') : T('st_bad')) + '</p><div class="x-row"><button type="button" class="pill-btn st-back">' + esc(T('st_back')) + '</button><button type="button" class="pill-btn primary st-retry">' + esc(T('st_retry')) + '</button></div></div>';
      $('.st-back', M.body).addEventListener('click', function () { home({ source: source, type: type }); });
      $('.st-retry', M.body).addEventListener('click', function () { run(type, source, count, diff); });
    });
  }
  function play(d) { if (d.type === 'flash') flash(d, d.items.slice()); else quiz(d, d.items.slice()); }

  /* ---------------- flashcards ---------------- */
  function flash(d, cards) {
    var i = 0, flipped = false, known = {}, missed = [], b = M.body, total = cards.length;
    function draw() {
      var c = cards[i];
      b.innerHTML = '<div class="fc-top"><button type="button" class="pill-btn fc-back"><i class="fa-solid fa-arrow-left"></i> ' + esc(T('st_back')) + '</button><span class="fc-n">' + esc(fmt('st_card_n', { n: i + 1, t: total })) + '</span><button type="button" class="icon-btn fc-shuf" aria-label="' + esc(T('st_shuffle')) + '" title="' + esc(T('st_shuffle')) + '"><i class="fa-solid fa-shuffle"></i></button></div>' +
        '<div class="st-bar"><i style="width:' + (i / total * 100) + '%"></i></div>' +
        '<button type="button" class="fc-card' + (flipped ? ' flipped' : '') + '" aria-live="polite"><span class="fc-side">' + esc(flipped ? 'A' : 'Q') + '</span><span class="fc-text">' + esc(flipped ? c.a : c.q) + '</span><span class="fc-tip">' + esc(T('st_flip')) + '</span></button>' +
        '<div class="fc-act"><button type="button" class="pill-btn fc-prev"' + (i === 0 ? ' disabled' : '') + '><i class="fa-solid fa-chevron-left"></i> ' + esc(T('st_prev')) + '</button>' +
        '<button type="button" class="pill-btn fc-no"' + (flipped ? '' : ' disabled') + '><i class="fa-solid fa-rotate"></i> ' + esc(T('st_learning')) + '</button><button type="button" class="pill-btn primary fc-yes"' + (flipped ? '' : ' disabled') + '><i class="fa-solid fa-check"></i> ' + esc(T('st_known')) + '</button></div>';
      $('.fc-back', b).addEventListener('click', function () { home({ source: d.source, type: 'flash' }); });
      $('.fc-shuf', b).addEventListener('click', function () { cards = shuffle(cards); i = 0; flipped = false; known = {}; missed = []; draw(); });
      $('.fc-card', b).addEventListener('click', flip);
      $('.fc-prev', b).addEventListener('click', function () { if (i > 0) { i--; flipped = false; draw(); } });
      $('.fc-yes', b).addEventListener('click', function () { mark(true); }); $('.fc-no', b).addEventListener('click', function () { mark(false); });
      var cd = $('.fc-card', b); if (cd) cd.focus({ preventScroll: true });
    }
    function flip() { flipped = !flipped; draw(); }
    function mark(ok) { if (!flipped) return; if (ok) known[i] = 1; else if (missed.indexOf(cards[i]) < 0) missed.push(cards[i]); next(); }
    function next() { if (i < total - 1) { i++; flipped = false; draw(); } else done(); }
    function done() {
      keyHandler = null; var k = Object.keys(known).length, m = total - k, all = m === 0, miss = cards.filter(function (c, idx) { return !known[idx]; });
      b.innerHTML = '<div class="st-end"><i class="fa-solid ' + (all ? 'fa-trophy' : 'fa-flag-checkered') + '"></i><h3>' + esc(all ? T('st_all_known') : T('st_done')) + '</h3><p>' + esc(fmt('st_known_n', { k: k, n: total })) + '</p><div class="x-row">' +
        '<button type="button" class="pill-btn st-again"><i class="fa-solid fa-rotate-left"></i> ' + esc(T('st_restart')) + '</button>' + (m ? '<button type="button" class="pill-btn primary st-miss"><i class="fa-solid fa-layer-group"></i> ' + esc(fmt('st_review_missed', { m: m })) + '</button>' : '') + '<button type="button" class="pill-btn st-home">' + esc(T('st_back')) + '</button></div></div>';
      $('.st-again', b).addEventListener('click', function () { flash(d, d.items.slice()); });
      var mb = $('.st-miss', b); if (mb) mb.addEventListener('click', function () { flash(d, miss); });
      $('.st-home', b).addEventListener('click', function () { home({}); });
      var f = $('.st-end button', b); if (f) f.focus();
    }
    keyHandler = function (e) {
      if (e.key === ' ' || e.key === 'Enter') { e.preventDefault(); flip(); }
      else if (e.key === 'ArrowRight') { if (flipped) { mark(false); } else { flipped = true; draw(); } }
      else if (e.key === 'ArrowLeft') { if (i > 0) { i--; flipped = false; draw(); } }
      else if (e.key === '1' || e.key === 'y') mark(true); else if (e.key === '2' || e.key === 'n') mark(false);
    };
    draw();
  }

  /* ---------------- scored quiz ---------------- */
  function quiz(d, items) {
    var i = 0, score = 0, streak = 0, best = 0, wrong = [], locked = false, b = M.body, total = items.length, LET = ['A', 'B', 'C', 'D'];
    function draw() {
      var q = items[i]; locked = false;
      b.innerHTML = '<div class="fc-top"><button type="button" class="pill-btn fc-back"><i class="fa-solid fa-arrow-left"></i> ' + esc(T('st_back')) + '</button><span class="fc-n">' + esc(fmt('st_question_n', { n: i + 1, t: total })) + '</span><span class="qz-score"><b>' + score + '</b> ' + esc(T('st_score')) + (streak > 1 ? ' · <span class="qz-fire">🔥 ' + streak + '</span>' : '') + '</span></div>' +
        '<div class="st-bar"><i style="width:' + (i / total * 100) + '%"></i></div><h3 class="qz-q">' + esc(q.q) + '</h3>' +
        '<div class="qz-opts" role="group" aria-label="' + esc(q.q) + '">' + q.options.map(function (o, k) { return '<button type="button" class="qz-opt" data-k="' + k + '"><span class="qz-l">' + LET[k] + '</span><span>' + esc(o) + '</span></button>'; }).join('') + '</div>' +
        '<div class="qz-fb" role="status" aria-live="polite" hidden></div><div class="x-row"><button type="button" class="pill-btn primary qz-next" disabled>' + esc(i === total - 1 ? T('st_finish') : T('st_next')) + ' <i class="fa-solid fa-arrow-right"></i></button></div>';
      $('.fc-back', b).addEventListener('click', function () { home({ source: d.source, type: 'quiz' }); });
      $$('.qz-opt', b).forEach(function (o) { o.addEventListener('click', function () { pick(+o.getAttribute('data-k')); }); });
      $('.qz-next', b).addEventListener('click', next);
    }
    function pick(k) {
      if (locked) return; locked = true; var q = items[i], ok = k === q.answer;
      $$('.qz-opt', b).forEach(function (o, n) { o.disabled = true; if (n === q.answer) o.classList.add('right'); else if (n === k) o.classList.add('wrong'); });
      if (ok) { score++; streak++; best = Math.max(best, streak); } else { streak = 0; wrong.push({ q: q, picked: k }); }
      var fb = $('.qz-fb', b); fb.hidden = false; fb.className = 'qz-fb ' + (ok ? 'ok' : 'bad');
      fb.innerHTML = '<b>' + esc(ok ? T('st_correct') : T('st_wrong')) + '</b>' + (ok ? '' : ' ' + esc(T('st_answer_is')) + ': <strong>' + LET[q.answer] + '. ' + esc(q.options[q.answer]) + '</strong>') + (q.why ? '<p>' + esc(q.why) + '</p>' : '');
      $('.qz-score', b).innerHTML = '<b>' + score + '</b> ' + esc(T('st_score')) + (streak > 1 ? ' · <span class="qz-fire">🔥 ' + streak + '</span>' : '');
      var nb = $('.qz-next', b); nb.disabled = false; nb.focus();
    }
    function next() { if (!locked) return; if (i < total - 1) { i++; draw(); } else finish(); }
    function finish() {
      keyHandler = null; var pct = Math.round(score / total * 100); if (d.best == null || pct > d.best) d.best = pct; d.plays = (d.plays || 0) + 1; save();
      b.innerHTML = '<div class="st-end"><div class="qz-ring" style="--p:' + pct + '"><b>' + pct + '%</b></div><h3>' + esc(T('st_result')) + '</h3><p>' + esc(T('st_score')) + ': <strong>' + score + ' / ' + total + '</strong>' + (best > 1 ? ' · ' + esc(T('st_streak')) + ': 🔥 ' + best : '') + ' · ' + esc(T('st_best')) + ': ' + d.best + '%</p>' +
        '<p class="st-msgline">' + esc(pct === 100 ? T('st_perfect') : pct >= 70 ? T('st_good') : pct >= 40 ? T('st_okay') : T('st_low')) + '</p><div class="x-row">' +
        (wrong.length ? '<button type="button" class="pill-btn primary st-retry-m"><i class="fa-solid fa-rotate"></i> ' + esc(T('st_retry_mistakes')) + '</button>' : '') + '<button type="button" class="pill-btn st-new"><i class="fa-solid fa-wand-magic-sparkles"></i> ' + esc(T('st_new_quiz')) + '</button><button type="button" class="pill-btn st-home">' + esc(T('st_back')) + '</button></div></div>' +
        (wrong.length ? '<h4 class="st-h">' + esc(T('st_mistakes')) + '</h4><div class="qz-rev">' + wrong.map(function (w) { return '<div class="qz-ri"><b>' + esc(w.q.q) + '</b><span class="bad">' + esc(T('st_your')) + ': ' + esc(w.q.options[w.picked]) + '</span><span class="ok">' + esc(T('st_answer_is')) + ': ' + esc(w.q.options[w.q.answer]) + '</span>' + (w.q.why ? '<em>' + esc(w.q.why) + '</em>' : '') + '</div>'; }).join('') + '</div>' : '');
      var rm = $('.st-retry-m', b); if (rm) rm.addEventListener('click', function () { quiz(d, shuffle(wrong.map(function (w) { return w.q; }))); });
      $('.st-new', b).addEventListener('click', function () { run('quiz', d.source, d.count || 8, d.diff || 'medium'); });
      $('.st-home', b).addEventListener('click', function () { home({}); });
    }
    keyHandler = function (e) {
      var k = 'abcd'.indexOf(e.key.toLowerCase()); if (k < 0 && /^[1-4]$/.test(e.key)) k = +e.key - 1;
      if (k >= 0 && k < items[i].options.length && !locked) { e.preventDefault(); pick(k); } else if ((e.key === 'Enter' || e.key === 'ArrowRight') && locked) { e.preventDefault(); next(); }
    };
    draw();
  }

  /* ---------------- entry points ---------------- */
  var sb = $('#studyBtn'); if (sb) sb.addEventListener('click', function () { open({}); });
  Chat.extraActions = function () { return '<button class="icon-btn" data-act="fc" title="' + esc(T('fc_btn')) + '" aria-label="' + esc(T('fc_btn')) + '"><i class="fa-solid fa-clone"></i></button><button class="icon-btn" data-act="qz" title="' + esc(T('qz_btn')) + '" aria-label="' + esc(T('qz_btn')) + '"><i class="fa-solid fa-circle-question"></i></button>'; };
  var prevAct = Chat.onAct;
  Chat.onAct = function (a, btn, msg, i) {
    if ((a === 'fc' || a === 'qz') && msg && msg.content) { open({ source: msg.content.replace(/```[\s\S]*?```/g, ' ').trim().slice(0, 6000), type: a === 'fc' ? 'flash' : 'quiz', auto: true }); return; }
    if (prevAct) prevAct(a, btn, msg, i);
  };
  Chat.openStudy = open;
  L.onChange(function () { if (M && !$('.st-load', M.body)) { /* keep the current screen; titles refresh on next open */ M.setTitle(T('st_title')); } });
})();
