/* Smart21Brain — Global Search
   Searches everything on the site: pages, games, videos, books, courses, lessons,
   kids content, cartoons, subjects and blog posts (js/search-index.js, generated by
   scripts/gen-search-index.mjs) plus live content from /api/search (database).
   - Typing shows instant suggestions in the dropdown.
   - Pressing Enter / the arrow opens search.html?q=… with ALL matches, grouped by type.
   - Works in English and Kiswahili (titles are indexed in both). */
(function () {
  const POPULAR = ['fractions', 'solar system', 'coding for kids', 'multiplication', 'kiswahili songs'];
  const HISTORY_KEY = 's21-search-history';
  const TYPE_ICON = {
    Course: 'fa-graduation-cap', Lesson: 'fa-book-open-reader', Game: 'fa-gamepad', Video: 'fa-circle-play',
    Book: 'fa-book', Kids: 'fa-child-reaching', Cartoon: 'fa-film', Subject: 'fa-shapes', Blog: 'fa-newspaper',
    Level: 'fa-layer-group', Quiz: 'fa-circle-question', Material: 'fa-file-lines', Page: 'fa-file', Section: 'fa-compass',
  };
  const TYPE_ORDER = ['Level', 'Course', 'Lesson', 'Video', 'Kids', 'Cartoon', 'Book', 'Game', 'Quiz', 'Subject', 'Blog', 'Material', 'Section', 'Page'];

  /* ---------- helpers ---------- */
  const esc = (s) => String(s == null ? '' : s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  const norm = (s) => String(s || '').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9\s]/g, ' ').replace(/\s+/g, ' ').trim();
  const typeRank = (t) => { const i = TYPE_ORDER.indexOf(t); return i < 0 ? 99 : i; };

  function getHistory() { try { return JSON.parse(localStorage.getItem(HISTORY_KEY)) || []; } catch { return []; } }
  function pushHistory(term) {
    try {
      const list = getHistory().filter((t) => t.toLowerCase() !== term.toLowerCase());
      list.unshift(term);
      localStorage.setItem(HISTORY_KEY, JSON.stringify(list.slice(0, 6)));
    } catch { /* storage unavailable */ }
  }

  /* ---------- index loading ---------- */
  const here = (document.currentScript && document.currentScript.src) || '';
  const indexUrl = here ? here.replace(/search\.js(\?.*)?$/, 'search-index.js') : 'js/search-index.js';
  let indexPromise;
  function loadIndex() {
    if (indexPromise) return indexPromise;
    indexPromise = new Promise((resolve) => {
      const build = () => resolve((window.S21_SEARCH_INDEX || []).map(([title, type, href, kw]) => ({
        title, type, href, kw, t: norm(title), k: norm(kw),
      })));
      if (window.S21_SEARCH_INDEX) return build();
      const s = document.createElement('script');
      s.src = indexUrl;
      s.onload = build;
      s.onerror = () => resolve([]);
      document.head.appendChild(s);
    });
    return indexPromise;
  }

  /* ---------- matching ---------- */
  function editDistanceLE1(a, b) {
    if (Math.abs(a.length - b.length) > 1) return false;
    let i = 0, j = 0, edits = 0;
    while (i < a.length && j < b.length) {
      if (a[i] === b[j]) { i++; j++; continue; }
      if (++edits > 1) return false;
      if (a.length > b.length) i++; else if (a.length < b.length) j++; else { i++; j++; }
    }
    return edits + (a.length - i) + (b.length - j) <= 1;
  }

  function scoreEntry(entry, tokens, fuzzy) {
    let total = 0;
    const tWords = entry.t.split(' ');
    const kWords = fuzzy ? entry.k.split(' ') : null;
    for (const tok of tokens) {
      let s = 0;
      if (entry.t === tok) s = 100;
      else if (entry.t.startsWith(tok)) s = 60;
      else if (tWords.some((w) => w.startsWith(tok))) s = 45;
      else if (entry.t.includes(tok)) s = 30;
      else if (entry.k.includes(tok)) s = 12;
      else if (fuzzy && tok.length >= 4 && (tWords.some((w) => editDistanceLE1(w, tok)) || kWords.some((w) => editDistanceLE1(w, tok)))) s = 8;
      if (!s) return 0; // every word typed must match somewhere
      total += s;
    }
    if (entry.t.includes(tokens.join(' '))) total += 25; // whole phrase in the title
    return total;
  }

  function searchIndex(index, query) {
    let tokens = norm(query).split(' ').filter(Boolean);
    const longer = tokens.filter((t) => t.length > 1);
    if (longer.length) tokens = longer; // ignore stray one-letter words like the "a" in "a level"
    if (!tokens.length) return [];
    const run = (fuzzy) => index
      .map((e) => ({ e, s: scoreEntry(e, tokens, fuzzy) }))
      .filter((r) => r.s > 0)
      .sort((a, b) => b.s - a.s || typeRank(a.e.type) - typeRank(b.e.type))
      .map((r) => r.e);
    const res = run(false);
    return res.length ? res : run(true);
  }

  async function searchApi(query) {
    if (query.trim().length < 2) return [];
    try {
      const response = await fetch(`/api/search?q=${encodeURIComponent(query)}`);
      if (!response.ok) return [];
      const data = await response.json();
      return (data.results || []).map((r) => ({ title: r.title, type: r.type || 'Material', href: r.href, kw: r.detail || '' }));
    } catch { return []; }
  }

  async function findAll(query) {
    const [index, api] = await Promise.all([loadIndex(), searchApi(query)]);
    const local = searchIndex(index, query);
    const seen = new Set(local.map((r) => `${r.type}|${norm(r.title)}`));
    return local.concat(api.filter((r) => !seen.has(`${r.type}|${norm(r.title)}`)));
  }

  /* ---------- rendering ---------- */
  const resultsUrl = (q) => `search.html?q=${encodeURIComponent(q)}`;
  const icon = (type) => `<i class="fa-solid ${TYPE_ICON[type] || 'fa-circle-dot'}"></i>`;

  function itemHtml(m) {
    return `<a href="${esc(m.href)}" class="s21-search-item">${icon(m.type)}<span class="s21-search-title">${esc(m.title)}</span><em>${esc(m.type)}</em></a>`;
  }

  function renderIdle(panel) {
    let html = '';
    const hist = getHistory();
    if (hist.length) {
      html += '<div class="s21-search-group"><span>Recent searches</span>';
      html += hist.map((h) => `<button type="button" class="s21-search-item s21-search-history-item"><i class="fa-solid fa-clock-rotate-left"></i><span class="s21-search-title">${esc(h)}</span></button>`).join('');
      html += '</div>';
    }
    html += '<div class="s21-search-group"><span>Popular right now</span><div class="s21-chip-row">';
    html += POPULAR.map((p) => `<button type="button" class="s21-search-chip s21-search-history-item"><i class="fa-solid fa-arrow-trend-up"></i>${esc(p)}</button>`).join('');
    html += '</div></div>';
    panel.innerHTML = html;
    panel.querySelectorAll('.s21-search-history-item').forEach((btn) => {
      btn.addEventListener('click', () => {
        const input = panel.closest('.s21-search-wrap').querySelector('input');
        input.value = btn.textContent.trim();
        input.dispatchEvent(new Event('input'));
        input.focus();
      });
    });
  }

  async function renderSuggestions(panel, query) {
    const q = query.trim();
    if (!q) { renderIdle(panel); return; }
    const matches = await findAll(q);
    if (panel.closest('.s21-search-wrap').querySelector('input').value.trim() !== q) return; // stale
    let html = '<div class="s21-search-group"><span>Results</span>';
    html += matches.length
      ? matches.slice(0, 8).map(itemHtml).join('')
      : '<p class="s21-search-empty">Nothing found for “' + esc(q) + '”. Try another word or check the spelling.</p>';
    html += '</div>';
    if (matches.length) {
      html += `<a class="s21-search-all" href="${resultsUrl(q)}"><i class="fa-solid fa-magnifying-glass"></i> See all ${matches.length} result${matches.length === 1 ? '' : 's'} for “${esc(q)}”</a>`;
    }
    panel.innerHTML = html;
  }

  /* Full results page (search.html) */
  async function renderFullResults(container, query) {
    const q = query.trim();
    if (!q) {
      container.innerHTML = '<p class="s21-res-empty">Type something above to search videos, books, games, courses, lessons and more.</p>';
      return;
    }
    container.innerHTML = '<p class="s21-res-empty"><i class="fa-solid fa-spinner fa-spin"></i> Searching…</p>';
    const all = await findAll(q);
    if (!all.length) {
      container.innerHTML = `<div class="s21-res-empty"><i class="fa-regular fa-face-frown" style="font-size:2rem"></i><h2 class="h5 mt-3">Nothing found for “${esc(q)}”</h2><p>Check the spelling or try a shorter word like “math”, “plants” or “coding”.</p></div>`;
      return;
    }
    const groups = {};
    all.forEach((r) => { (groups[r.type] = groups[r.type] || []).push(r); });
    const types = Object.keys(groups).sort((a, b) => typeRank(a) - typeRank(b));
    const chips = ['All'].concat(types).map((t, i) => {
      const n = t === 'All' ? all.length : groups[t].length;
      return `<button type="button" class="s21-res-filter${i === 0 ? ' active' : ''}" data-type="${esc(t)}">${esc(t)} <b>${n}</b></button>`;
    }).join('');
    const sections = types.map((t) => `
      <section class="s21-res-group" data-type="${esc(t)}">
        <h2 class="s21-res-head">${icon(t)} ${esc(t)} <small>${groups[t].length}</small></h2>
        <div class="s21-res-list">${groups[t].map((r) => `
          <a href="${esc(r.href)}" class="s21-res-card">
            <span class="s21-res-ico">${icon(r.type)}</span>
            <span class="s21-res-body"><strong>${esc(r.title)}</strong>${r.kw ? `<small>${esc(r.kw.length > 110 ? r.kw.slice(0, 107) + '…' : r.kw)}</small>` : ''}</span>
            <i class="fa-solid fa-chevron-right s21-res-go"></i>
          </a>`).join('')}</div>
      </section>`).join('');
    container.innerHTML = `<p class="s21-res-count">${all.length} result${all.length === 1 ? '' : 's'} for “${esc(q)}”</p>
      <div class="s21-res-filters">${chips}</div>${sections}`;
    container.querySelectorAll('.s21-res-filter').forEach((btn) => {
      btn.addEventListener('click', () => {
        container.querySelectorAll('.s21-res-filter').forEach((b) => b.classList.toggle('active', b === btn));
        const t = btn.dataset.type;
        container.querySelectorAll('.s21-res-group').forEach((g) => { g.hidden = t !== 'All' && g.dataset.type !== t; });
      });
    });
  }

  /* ---------- wiring ---------- */
  document.addEventListener('DOMContentLoaded', () => {
    loadIndex(); // warm the index
    const fullBox = document.getElementById('s21-search-results');
    const params = new URLSearchParams(location.search);

    document.querySelectorAll('.s21-search-wrap').forEach((wrap) => {
      const input = wrap.querySelector('input');
      const panel = wrap.querySelector('.s21-search-panel');
      if (!input || !panel) return;
      input.setAttribute('autocomplete', 'off');

      // Let the dropdown hang outside banners/sections that clip their content (overflow:hidden).
      for (let el = wrap.parentElement; el && el !== document.body; el = el.parentElement) {
        const o = getComputedStyle(el);
        if (o.overflow !== 'visible' || o.overflowY !== 'visible') el.classList.add('s21-search-host');
      }

      if (fullBox) {
        input.value = params.get('q') || '';
        renderFullResults(fullBox, input.value);
      }

      input.addEventListener('focus', () => { if (!fullBox) { panel.classList.add('open'); renderSuggestions(panel, input.value); } });
      let searchTimer;
      input.addEventListener('input', () => {
        panel.classList.add('open');
        clearTimeout(searchTimer);
        searchTimer = setTimeout(() => renderSuggestions(panel, input.value), 120);
      });
      input.addEventListener('keydown', (e) => { if (e.key === 'Escape') panel.classList.remove('open'); });
      document.addEventListener('click', (e) => { if (!wrap.contains(e.target)) panel.classList.remove('open'); });

      // The wrap IS the <form> in this site; fall back to a child form just in case.
      const form = wrap.tagName === 'FORM' ? wrap : wrap.querySelector('form');
      (form || wrap).addEventListener('submit', (e) => {
        e.preventDefault();
        const q = input.value.trim();
        panel.classList.remove('open');
        if (!q) return;
        pushHistory(q);
        if (fullBox) {
          history.replaceState(null, '', resultsUrl(q));
          document.title = `${q} — Search | Smart21Brain`;
          renderFullResults(fullBox, q);
        } else if (!wrap.hasAttribute('data-local-search')) {
          location.href = resultsUrl(q); // pages with their own list filter (data-local-search) keep it
        }
      });
    });
  });

  window.S21Search = { search: findAll, norm };
})();
