/* Fees & Payments: balances overview, payment history, fee structure, receipts. */
(function () {
  'use strict';
  const SC = window.SC; const esc = SC.esc;
  const FEE_TYPES = () => [['registration', SC.t('Registration fee', 'Ada ya Usajili')], ['tuition', SC.t('Tuition fee', 'Ada ya Masomo')], ['examination', SC.t('Examination fee', 'Ada ya Mtihani')], ['other', SC.t('Other fee', 'Ada Nyingine')]];
  const docColor = () => `--doc-color:${SC.state.school.primary_color || '#0B6E4F'}`;

  // ------------------------------------------------------------ receipt
  function receiptHtml(r) {
    const s = r.school;
    return `<div class="sc-doc sc-receipt" style="${docColor()}"><div class="hd"><span class="lg">${esc(SC.schoolInitials(s))}${s.has_logo ? `<img src="${SC.logoUrl(s.id)}" alt="" onerror="this.remove()">` : ''}</span><div><h4>${esc(s.name)}</h4><div class="meta">${esc([s.address, s.phone, s.email].filter(Boolean).join(' · '))}</div></div></div>
      <div class="title">${SC.t('PAYMENT RECEIPT', 'RISITI YA MALIPO')}</div><div class="meta" style="text-align:center;margin-bottom:10px">${SC.t('Receipt No.', 'Namba ya Risiti')} <b style="color:#111">${esc(r.receipt_no)}</b></div>
      <table><tr><td>${SC.t('Date', 'Tarehe')}</td><td>${SC.date(r.payment_date)}</td></tr><tr><td>${SC.t('Student', 'Mwanafunzi')}</td><td>${esc(r.student.name)}</td></tr><tr><td>${SC.t('Student ID', 'Namba ya Mwanafunzi')}</td><td>${esc(r.student.admission_no)}</td></tr><tr><td>${SC.t('Class', 'Darasa')}</td><td>${esc(r.student.class_name)}</td></tr>
      <tr><td>${SC.t('Payment method', 'Njia ya Malipo')}</td><td>${esc(r.method)}</td></tr><tr><td>${SC.t('Reference / transaction no.', 'Kumbukumbu / Namba ya Muamala')}</td><td>${esc(r.reference || '—')}</td></tr><tr><td>${SC.t('Received by', 'Alipokelewa na')}</td><td>${esc(r.received_by || '—')}</td></tr></table>
      <div class="amt"><span class="meta">${SC.t('Amount paid', 'Kiasi Kilicholipwa')}</span><b>${SC.num(r.amount)} ${esc(r.currency)}</b></div>
      <table><tr><td>${SC.t('Total fees', 'Jumla ya Ada')}</td><td>${SC.num(r.total_fees)} ${esc(r.currency)}</td></tr><tr><td>${SC.t('Paid to date', 'Ililipwa Hadi Sasa')}</td><td>${SC.num(r.paid_to_date)} ${esc(r.currency)}</td></tr><tr><td>${SC.t('Remaining balance', 'Deni Lililobaki')}</td><td style="color:${r.balance > 0 ? '#c0392b' : '#12805C'}">${SC.num(r.balance)} ${esc(r.currency)}</td></tr></table>
      ${r.notes ? `<div class="meta" style="margin-top:8px">${SC.t('Notes', 'Maelezo')}: ${esc(r.notes)}</div>` : ''}<div class="foot">${esc(r.footer || '')}<br>${SC.t('This receipt was generated by the school system and is valid without a signature.', 'Risiti hii imetengenezwa na mfumo wa shule na ni halali bila sahihi.')}</div></div>`;
  }
  SC.receiptModal = async (paymentId) => {
    const { receipt } = await SC.api.get(`/payments/${paymentId}/receipt`);
    const back = SC.modal(SC.t(`Receipt ${receipt.receipt_no}`, `Risiti ${receipt.receipt_no}`), `<div class="sc-doc-stage" id="rcptStage">${receiptHtml(receipt)}</div>`, {
      footer: `<button class="sc-btn ghost" data-close2>${SC.t('Close', 'Funga')}</button><button class="sc-btn ghost" data-pdf><i class="fa-solid fa-file-pdf"></i> ${SC.t('Download PDF', 'Pakua PDF')}</button><button class="sc-btn primary" data-print><i class="fa-solid fa-print"></i> ${SC.t('Print receipt', 'Chapisha Risiti')}</button>`,
    });
    back.querySelector('[data-close2]').onclick = () => SC.closeModal();
    back.querySelector('[data-print]').onclick = () => SC.print(`<div style="display:flex;justify-content:center">${receiptHtml(receipt)}</div>`);
    back.querySelector('[data-pdf]').onclick = async (e) => {
      const b = e.currentTarget; b.disabled = true;
      try { await SC.pdf(back.querySelector('.sc-receipt'), `Receipt-${receipt.receipt_no}.pdf`, { format: 'a5', margin: 10 }); SC.toast(SC.t('Receipt downloaded.', 'Risiti imepakuliwa.')); } catch (err) { SC.fail(err); } finally { b.disabled = false; }
    };
  };

  // ------------------------------------------------------------ record payment
  SC.payModal = async ({ studentId = null, onDone } = {}) => {
    const methods = SC.state.settings.payment_methods || ['Cash', 'Bank', 'Mobile Money', 'Card', 'Other'];
    let student = null;
    if (studentId) {
      const [{ student: s }, fees] = await Promise.all([SC.api.get(`/students/${studentId}`), SC.api.get(`/students/${studentId}/fees`)]);
      student = { id: s.id, name: s.full_name, admission_no: s.admission_no, balance: fees.summary.balance, total: fees.summary.total, cls: s.class ? SC.classLabel(s.class) : '' };
    }
    const back = SC.formModal({
      title: SC.t('Record payment', 'Rekodi Malipo'), size: 'wide', submit: SC.t('Save payment & create receipt', 'Hifadhi Malipo na Tengeneza Risiti'),
      body: `<div id="stuBox">${student ? '' : `<div class="sc-field"><label for="sQ">${SC.t('Student', 'Mwanafunzi')} <span class="req">*</span></label><input class="sc-input" id="sQ" type="search" placeholder="${SC.t("Type the student's name or ID…", 'Andika jina la mwanafunzi au namba…')}" autocomplete="off"><div id="sRes" class="sc-list"></div></div>`}</div>
        <div id="stuInfo"></div>
        <div class="cols">${SC.f.input('amount', SC.t('Amount', 'Kiasi'), { type: 'number', required: true, attr: { min: 1, step: '0.01' }, placeholder: '0' })}${SC.f.input('payment_date', SC.t('Payment date', 'Tarehe ya Malipo'), { type: 'date', required: true, value: SC.today(), attr: { max: SC.today() } })}</div>
        <div class="cols">${SC.f.select('method', SC.t('Payment method', 'Njia ya Malipo'), methods.map((m) => [m, m]), { required: true, value: methods[0], noBlank: true })}${SC.f.input('reference', SC.t('Reference / transaction number', 'Kumbukumbu / Namba ya Muamala'), { placeholder: SC.t('Required for Bank, Mobile Money and Card', 'Inahitajika kwa Benki, Pesa za Simu na Kadi') })}</div>
        <div class="cols">${SC.f.input('received_by', SC.t('Received by', 'Alipokelewa na'), { value: SC.state.user.name, attr: { readonly: true } })}${SC.f.input('notes', SC.t('Notes', 'Maelezo'), { placeholder: SC.t('Optional', 'Si lazima') })}</div>`,
      onSubmit: async (f) => {
        if (!student) throw new Error(SC.t('Please choose the student who is paying.', 'Tafadhali chagua mwanafunzi anayelipa.'));
        const r = await SC.api.post('/payments', { student_id: student.id, amount: Number(f.amount), payment_date: f.payment_date, method: f.method, reference: f.reference, notes: f.notes });
        SC.closeModal();
        const done = SC.modal(SC.t('Payment recorded', 'Malipo Yamerekodiwa'), `<div class="sc-center"><div class="sc-empty" style="padding:.5rem 0"><div class="ico" style="background:var(--sc-ok-bg);color:var(--sc-ok)"><i class="fa-solid fa-circle-check"></i></div><h4>${SC.t('Payment recorded successfully.', 'Malipo yamerekodiwa kwa mafanikio.')}</h4><p style="margin:0 auto">${SC.t('Receipt', 'Risiti')} <b>${esc(r.receipt_no)}</b> · ${SC.t('Remaining balance', 'Deni Lililobaki')} <b>${SC.money(r.balance)}</b></p></div></div>`, {
          footer: `<button class="sc-btn ghost" data-x>${SC.t('Close', 'Funga')}</button><button class="sc-btn primary" data-r><i class="fa-solid fa-receipt"></i> ${SC.t('View / Print receipt', 'Ona / Chapisha Risiti')}</button>` });
        done.querySelector('[data-x]').onclick = () => { SC.closeModal(); if (onDone) onDone(r); };
        done.querySelector('[data-r]').onclick = () => { SC.closeModal(); SC.receiptModal(r.id); if (onDone) onDone(r); };
      },
    });
    const info = back.querySelector('#stuInfo');
    const showStudent = (s) => {
      student = s;
      info.innerHTML = `<div class="sc-alert info"><i class="fa-solid fa-user-graduate"></i><div class="sc-spread" style="flex:1"><div><b>${esc(s.name)}</b> · ${esc(s.admission_no)}${s.cls ? ' · ' + esc(s.cls) : ''}<div class="sc-small">${SC.t('Total fees', 'Jumla ya Ada')} ${SC.money(s.total)} · ${SC.t('Outstanding balance', 'Deni Lililobaki')} <b>${SC.money(s.balance)}</b></div></div>${studentId ? '' : `<button type="button" class="sc-btn ghost sm" data-change>${SC.t('Change', 'Badilisha')}</button>`}</div></div>`;
      const amt = back.querySelector('[name=amount]'); amt.max = s.balance; if (s.balance > 0) amt.placeholder = SC.t(`Up to ${SC.num(s.balance)}`, `Hadi ${SC.num(s.balance)}`);
      const box = back.querySelector('#stuBox'); if (box && !studentId) box.classList.add('sc-hide');
      const ch = info.querySelector('[data-change]'); if (ch) ch.onclick = () => { student = null; info.innerHTML = ''; box.classList.remove('sc-hide'); back.querySelector('#sQ').focus(); };
    };
    if (student) showStudent(student);
    else {
      const run = SC.debounce(async () => {
        const q = back.querySelector('#sQ').value.trim(); const box = back.querySelector('#sRes');
        if (q.length < 2) { box.innerHTML = ''; return; }
        try {
          const d = await SC.api.get('/fees/overview' + SC.qs({ q, limit: 6 }));
          box.innerHTML = d.students.length ? d.students.map((s) => `<div class="sc-spread"><div><b>${esc(s.full_name)}</b><div class="sc-small sc-muted">${esc(s.admission_no)} · ${esc(s.class_name)} · ${SC.t('Balance', 'Deni')} ${SC.num(s.balance)}</div></div><button type="button" class="sc-btn primary sm" data-pick="${s.student_id}" data-n="${esc(s.full_name)}" data-a="${esc(s.admission_no)}" data-c="${esc(s.class_name)}" data-b="${s.balance}" data-t="${s.total}">${SC.t('Choose', 'Chagua')}</button></div>`).join('') : `<div class="sc-muted sc-small" style="padding:.5rem 0">${SC.t('No student found.', 'Hakuna mwanafunzi aliyepatikana.')}</div>`;
        } catch (e) { box.innerHTML = `<div class="sc-form-error show">${esc(e.message)}</div>`; }
      }, 250);
      back.querySelector('#sQ').addEventListener('input', run);
      back.addEventListener('click', (e) => { const b = e.target.closest('[data-pick]'); if (b) showStudent({ id: Number(b.dataset.pick), name: b.dataset.n, admission_no: b.dataset.a, cls: b.dataset.c, balance: Number(b.dataset.b), total: Number(b.dataset.t) }); });
    }
  };

  // ------------------------------------------------------------ fee structure modal
  async function feeModal(f, done) {
    const lk = await SC.lookups(); const isEdit = !!f;
    SC.formModal({
      title: isEdit ? SC.t('Edit fee', 'Hariri Ada') : SC.t('Add fee', 'Ongeza Ada'), submit: isEdit ? SC.t('Save changes', 'Hifadhi Mabadiliko') : SC.t('Add fee', 'Ongeza Ada'),
      body: `<div class="cols">${SC.f.input('name', SC.t('Fee name', 'Jina la Ada'), { required: true, value: f ? f.name : '', placeholder: SC.t('e.g. Tuition — Term 1', 'mfano: Ada ya Masomo — Muhula wa 1') })}${SC.f.select('fee_type', SC.t('Fee type', 'Aina ya Ada'), FEE_TYPES(), { required: true, value: f ? f.fee_type : 'tuition', noBlank: true })}</div>
        <div class="cols">${SC.f.input('amount', SC.t('Amount', 'Kiasi'), { type: 'number', required: true, value: f ? f.amount : '', attr: { min: 0, step: '0.01' } })}${SC.f.input('due_date', SC.t('Due date', 'Tarehe ya Mwisho'), { type: 'date', value: f ? f.due_date || '' : '', hint: SC.t('Unpaid fees become "Overdue" after this date.', 'Ada zisizolipwa zitakuwa "Zimechelewa" baada ya tarehe hii.') })}</div>
        <div class="cols">${SC.f.select('class_id', SC.t('Applies to', 'Inatumika kwa'), SC.opts.classes(lk, false), { value: f ? f.class_id || '' : '', placeholder: SC.t('All classes', 'Madarasa yote') })}${isEdit ? '' : SC.f.select('academic_year_id', SC.t('Academic year', 'Mwaka wa Masomo'), SC.opts.years(lk), { value: (lk.years.find((y) => y.is_current) || {}).id, noBlank: true })}</div>`,
      onSubmit: async (v) => {
        const body = { name: v.name, fee_type: v.fee_type, amount: Number(v.amount), due_date: v.due_date || null, class_id: v.class_id || null, academic_year_id: v.academic_year_id };
        if (isEdit) await SC.api.put(`/fees/structures/${f.id}`, body); else await SC.api.post('/fees/structures', body);
        SC.closeModal(); SC.toast(isEdit ? SC.t('Fee updated successfully.', 'Ada imesasishwa kwa mafanikio.') : SC.t('Fee added successfully.', 'Ada imeongezwa kwa mafanikio.')); done();
      },
    });
  }

  async function paymentEditModal(p, done) {
    const methods = SC.state.settings.payment_methods;
    SC.formModal({
      title: SC.t(`Edit payment ${p.receipt_no || ''}`, `Hariri Malipo ${p.receipt_no || ''}`), submit: SC.t('Save changes', 'Hifadhi Mabadiliko'),
      body: `<div class="sc-alert info"><i class="fa-solid fa-circle-info"></i><div>${SC.t('Changes to payments are recorded in the audit log.', 'Mabadiliko ya malipo yanarekodiwa kwenye kumbukumbu za ukaguzi.')}</div></div><div class="cols">${SC.f.input('amount', SC.t('Amount', 'Kiasi'), { type: 'number', required: true, value: p.amount, attr: { min: 0.01, step: '0.01' } })}${SC.f.input('payment_date', SC.t('Payment date', 'Tarehe ya Malipo'), { type: 'date', required: true, value: p.payment_date, attr: { max: SC.today() } })}</div>
        <div class="cols">${SC.f.select('method', SC.t('Method', 'Njia'), methods.map((m) => [m, m]), { value: p.method, noBlank: true })}${SC.f.input('reference', SC.t('Reference', 'Kumbukumbu'), { value: p.reference || '' })}</div>${SC.f.input('notes', SC.t('Notes', 'Maelezo'), { value: p.notes || '' })}`,
      onSubmit: async (v) => { await SC.api.put(`/payments/${p.id}`, { ...v, amount: Number(v.amount) }); SC.closeModal(); SC.toast(SC.t('Payment updated.', 'Malipo yamesasishwa.')); done(); },
    });
  }

  // ------------------------------------------------------------ main screen
  SC.modules.fees = async (el, args, seg) => {
    const lk = await SC.lookups();
    let tab = 'overview'; const st = { q: '', class_id: '', status: '', page: 1, limit: 20 }; const pst = { q: '', method: '', from: '', to: '', page: 1, limit: 20 };
    const methods = SC.state.settings.payment_methods || [];
    el.innerHTML = `${SC.pageHead(SC.t('Fees & Payments', 'Ada na Malipo'), SC.t('Balances, payments, receipts and the fee structure', 'Madeni, malipo, risiti na muundo wa ada'), `${SC.can('fees.manage') || SC.can('announcements.manage') ? `<button class="sc-btn ghost" data-act="remind"><i class="fa-solid fa-paper-plane"></i> ${SC.t('Send fee reminders', 'Tuma Vikumbusho vya Ada')}</button>` : ''}${SC.can('fees.record') ? `<button class="sc-btn primary" data-act="pay"><i class="fa-solid fa-plus"></i> ${SC.t('Record Payment', 'Rekodi Malipo')}</button>` : ''}`)}
      <div id="feeKpis"></div>
      <div class="sc-tabs" id="feeTabs"><button class="on" data-tab="overview">${SC.t('Student balances', 'Madeni ya Wanafunzi')}</button><button data-tab="payments">${SC.t('Payments & receipts', 'Malipo na Risiti')}</button>${SC.can('fees.manage') ? `<button data-tab="structure">${SC.t('Fee structure', 'Muundo wa Ada')}</button>` : ''}</div><div id="feeBody">${SC.skeleton(6)}</div>`;
    const body = el.querySelector('#feeBody');

    async function overview() {
      const d = await SC.api.get('/fees/overview' + SC.qs(st)); const s = d.summary;
      el.querySelector('#feeKpis').innerHTML = `<div class="sc-grid stats" style="margin-bottom:1.1rem">${SC.stat('fa-file-invoice-dollar', SC.money(s.total_fees), SC.t('Total fees expected', 'Jumla ya Ada Zinazotarajiwa'))}${SC.stat('fa-sack-dollar', SC.money(s.total_paid), SC.t('Total collected', 'Jumla Iliyokusanywa'), '', 'green')}${SC.stat('fa-scale-unbalanced', SC.money(s.outstanding), SC.t('Outstanding', 'Zinazodaiwa'), SC.t(`${s.counts.overdue} overdue`, `Zimechelewa ${s.counts.overdue}`), 'red')}${SC.stat('fa-users', `${s.counts.paid} / ${s.counts.partial} / ${s.counts.pending} / ${s.counts.overdue}`, SC.t('Paid / Partial / Pending / Overdue', 'Imelipwa / Sehemu / Inasubiri / Imechelewa'), SC.t('Students by status', 'Wanafunzi kwa hali'), 'blue')}</div>`;
      body.innerHTML = `<div class="sc-card"><div class="sc-toolbar"><input class="sc-input grow" id="oQ" type="search" placeholder="${SC.t('Search student name or ID…', 'Tafuta jina la mwanafunzi au namba…')}" value="${esc(st.q)}">
        <select class="sc-select" id="oClass"><option value="">${SC.t('All classes', 'Madarasa yote')}</option>${SC.opts.classes(lk, false).map((o) => `<option value="${o.v}" ${String(o.v) === String(st.class_id) ? 'selected' : ''}>${esc(o.l)}</option>`).join('')}</select>
        <select class="sc-select" id="oStatus"><option value="">${SC.t('Any status', 'Hali yoyote')}</option>${[['paid', SC.t('Paid', 'Imelipwa')], ['partial', SC.t('Partially Paid', 'Imelipwa Sehemu')], ['pending', SC.t('Pending', 'Inasubiri')], ['overdue', SC.t('Overdue', 'Imechelewa')]].map(([v, l]) => `<option value="${v}" ${st.status === v ? 'selected' : ''}>${l}</option>`).join('')}</select></div>
        ${SC.table([
          { label: SC.t('Student', 'Mwanafunzi'), render: (r) => `<a href="#student/${r.student_id}" class="sc-person"><span><span class="nm" style="color:var(--sc-text)">${esc(r.full_name)}</span><div class="sb sc-muted">${esc(r.admission_no)}</div></span></a>` },
          { label: SC.t('Class', 'Darasa'), render: (r) => esc(r.class_name) }, { label: SC.t('Parent', 'Mzazi'), render: (r) => `${esc(r.parent_name || '—')}<div class="sc-small sc-muted">${esc(r.parent_phone || '')}</div>` },
          { label: SC.t('Total fees', 'Jumla ya Ada'), cls: 'end', render: (r) => SC.num(r.total) }, { label: SC.t('Paid', 'Ililipwa'), cls: 'end', render: (r) => SC.num(r.paid) }, { label: SC.t('Balance', 'Deni'), cls: 'end', render: (r) => `<b>${SC.num(r.balance)}</b>` },
          { label: SC.t('Status', 'Hali'), render: (r) => SC.chip(r.status) },
          { label: '', cls: 'end', render: (r) => SC.can('fees.record') && r.balance > 0 ? `<button class="sc-btn soft sm" data-act="paystu" data-id="${r.student_id}"><i class="fa-solid fa-plus"></i> ${SC.t('Pay', 'Lipa')}</button>` : '' },
        ], d.students, { empty: SC.empty('fa-coins', SC.t('No students to show', 'Hakuna wanafunzi wa kuonyesha'), st.q || st.status || st.class_id ? SC.t('No student matches these filters.', 'Hakuna mwanafunzi anayelingana na vichujio hivi.') : SC.t('Register students and set a fee structure to see balances.', 'Sajili wanafunzi na weka muundo wa ada kuona madeni.')) })}${SC.pager(d.page, d.limit, d.total)}</div>`;
      body.querySelector('#oQ').addEventListener('input', SC.debounce((e) => { st.q = e.target.value.trim(); st.page = 1; draw(); }, 300));
      body.querySelector('#oClass').addEventListener('change', (e) => { st.class_id = e.target.value; st.page = 1; draw(); });
      body.querySelector('#oStatus').addEventListener('change', (e) => { st.status = e.target.value; st.page = 1; draw(); });
    }
    async function payments() {
      el.querySelector('#feeKpis').innerHTML = '';
      const d = await SC.api.get('/payments' + SC.qs(pst));
      body.innerHTML = `<div class="sc-card"><div class="sc-toolbar"><input class="sc-input grow" id="pyQ" type="search" placeholder="${SC.t('Search student, receipt number or reference…', 'Tafuta mwanafunzi, namba ya risiti au kumbukumbu…')}" value="${esc(pst.q)}">
        <select class="sc-select" id="pyM"><option value="">${SC.t('All methods', 'Njia zote')}</option>${methods.map((m) => `<option ${pst.method === m ? 'selected' : ''}>${esc(m)}</option>`).join('')}</select>
        <input class="sc-input" id="pyF" type="date" value="${pst.from}" title="${SC.t('From date', 'Kuanzia tarehe')}" aria-label="${SC.t('From date', 'Kuanzia tarehe')}"><input class="sc-input" id="pyT" type="date" value="${pst.to}" title="${SC.t('To date', 'Hadi tarehe')}" aria-label="${SC.t('To date', 'Hadi tarehe')}"></div>
        <div class="sc-small sc-muted" style="margin-bottom:.6rem">${SC.t(`${d.total} payment${d.total === 1 ? '' : 's'} · Total`, `Malipo ${d.total} · Jumla`)} <b>${SC.money(d.sum)}</b></div>
        ${SC.table([
          { label: SC.t('Date', 'Tarehe'), render: (r) => SC.date(r.payment_date) }, { label: SC.t('Receipt', 'Risiti'), render: (r) => `<b>${esc(r.receipt_no || '—')}</b>` },
          { label: SC.t('Student', 'Mwanafunzi'), render: (r) => `<a href="#student/${r.student_id}">${esc(r.student_name)}</a><div class="sc-small sc-muted">${esc(r.admission_no)}</div>` },
          { label: SC.t('Method', 'Njia'), render: (r) => esc(r.method) }, { label: SC.t('Reference', 'Kumbukumbu'), render: (r) => esc(r.reference || '—') }, { label: SC.t('Received by', 'Alipokelewa na'), render: (r) => esc(r.received_by_name || '—') },
          { label: SC.t('Amount', 'Kiasi'), cls: 'end', render: (r) => `<b>${SC.num(r.amount)}</b>` },
          { label: '', cls: 'end', render: (r) => `<div class="sc-actions-cell"><button class="sc-btn ghost sm" data-act="receipt" data-id="${r.id}"><i class="fa-solid fa-receipt"></i> ${SC.t('Receipt', 'Risiti')}</button>${SC.can('fees.manage') ? `<button class="sc-btn ghost sm" data-act="editpay" data-id="${r.id}"><i class="fa-solid fa-pen"></i></button>` : ''}</div>` },
        ], d.payments, { empty: SC.empty('fa-receipt', SC.t('No payments found', 'Hakuna malipo yaliyopatikana'), SC.t('Payments you record will be listed here with their receipts.', 'Malipo utakayorekodi yataorodheshwa hapa pamoja na risiti zake.')) })}${SC.pager(d.page, d.limit, d.total)}</div>`;
      body._pay = d.payments;
      const bindP = (id, k, ev = 'change') => body.querySelector(id).addEventListener(ev, (e) => { pst[k] = e.target.value.trim(); pst.page = 1; draw(); });
      body.querySelector('#pyQ').addEventListener('input', SC.debounce((e) => { pst.q = e.target.value.trim(); pst.page = 1; draw(); }, 300)); bindP('#pyM', 'method'); bindP('#pyF', 'from'); bindP('#pyT', 'to');
    }
    async function structure() {
      el.querySelector('#feeKpis').innerHTML = '';
      const d = await SC.api.get('/fees/structures');
      const total = d.structures.filter((x) => !x.class_id).reduce((s, x) => s + x.amount, 0);
      body.innerHTML = `<div class="sc-card"><div class="sc-card-head"><h3>${SC.t('Fee structure — current academic year', 'Muundo wa Ada — Mwaka wa Sasa wa Masomo')}</h3><div class="sc-actions"><button class="sc-btn primary sm" data-act="addfee"><i class="fa-solid fa-plus"></i> ${SC.t('Add fee', 'Ongeza Ada')}</button></div></div>
        <div class="sc-alert info" style="margin-bottom:1rem"><i class="fa-solid fa-circle-info"></i><div>${SC.t(`A student's <b>total fees</b> is the sum of every fee that applies to their class. Fees for "All classes" add up to <b>${SC.money(total)}</b>. Balances update automatically when you change this list.`, `<b>Jumla ya ada</b> ya mwanafunzi ni jumla ya kila ada inayotumika kwa darasa lake. Ada za "Madarasa yote" jumla yake ni <b>${SC.money(total)}</b>. Madeni yanasasishwa kiotomatiki unapobadilisha orodha hii.`)}</div></div>
        ${SC.table([{ label: SC.t('Fee', 'Ada'), render: (f) => `<b>${esc(f.name)}</b>` }, { label: SC.t('Type', 'Aina'), render: (f) => SC.cap(f.fee_type) }, { label: SC.t('Applies to', 'Inatumika kwa'), render: (f) => f.class_id ? esc(SC.classLabel({ name: f.class_name, stream: f.class_stream })) : SC.t('All classes', 'Madarasa yote') }, { label: SC.t('Due date', 'Tarehe ya Mwisho'), render: (f) => f.due_date ? SC.date(f.due_date) : '—' }, { label: SC.t('Amount', 'Kiasi'), cls: 'end', render: (f) => `<b>${SC.num(f.amount)}</b>` },
          { label: '', cls: 'end', render: (f) => `<div class="sc-actions-cell"><button class="sc-btn ghost sm" data-act="editfee" data-id="${f.id}"><i class="fa-solid fa-pen"></i></button><button class="sc-btn danger-ghost sm" data-act="delfee" data-id="${f.id}" data-name="${esc(f.name)}"><i class="fa-solid fa-trash"></i></button></div>` }],
        d.structures, { empty: SC.empty('fa-list-check', SC.t('No fees yet', 'Hakuna ada bado'), SC.t('Add registration, tuition, examination or other fees.', 'Ongeza ada za usajili, masomo, mtihani au nyingine.'), `<button class="sc-btn primary" data-act="addfee"><i class="fa-solid fa-plus"></i> ${SC.t('Add fee', 'Ongeza Ada')}</button>`) })}</div>`;
      body._fees = d.structures;
    }
    async function draw() { body.style.opacity = '.6'; try { await ({ overview, payments, structure })[tab](); } catch (e) { body.innerHTML = SC.errorBox(e); } body.style.opacity = '1'; }

    el.querySelector('#feeTabs').addEventListener('click', (e) => { const b = e.target.closest('button'); if (!b) return; tab = b.dataset.tab; el.querySelectorAll('#feeTabs button').forEach((x) => x.classList.toggle('on', x === b)); body.innerHTML = SC.skeleton(6); draw(); });
    SC.delegate(el, {
      page: (b) => { (tab === 'overview' ? st : pst).page = Number(b.dataset.p); draw(); },
      pay: () => SC.payModal({ onDone: draw }), paystu: (b) => SC.payModal({ studentId: b.dataset.id, onDone: draw }),
      receipt: (b) => SC.receiptModal(b.dataset.id),
      editpay: (b) => paymentEditModal(body._pay.find((p) => String(p.id) === b.dataset.id), draw),
      addfee: () => feeModal(null, draw), editfee: (b) => feeModal(body._fees.find((f) => String(f.id) === b.dataset.id), draw),
      delfee: async (b) => { if (!(await SC.confirm({ title: SC.t('Delete this fee?', 'Futa ada hii?'), message: SC.t(`<b>${esc(b.dataset.name)}</b> will be removed and every affected student's balance will be recalculated. Payments already recorded are kept.`, `<b>${esc(b.dataset.name)}</b> itaondolewa na deni la kila mwanafunzi aliyeathirika litahesabiwa upya. Malipo yaliyokwisha kurekodiwa yatabaki.`), confirmText: SC.t('Yes, delete fee', 'Ndiyo, futa ada') }))) return; await SC.api.del(`/fees/structures/${b.dataset.id}`); SC.toast(SC.t('Fee deleted.', 'Ada imefutwa.')); draw(); },
      remind: async () => {
        if (!(await SC.confirm({ title: SC.t('Send fee reminders?', 'Tuma vikumbusho vya ada?'), message: SC.t('Every student with <b>overdue</b> fees gets a fee reminder that their parent sees in the portal. Students reminded in the last 7 days are skipped.', 'Kila mwanafunzi mwenye ada <b>zilizochelewa</b> atapata kikumbusho cha ada ambacho mzazi wake ataona kwenye akaunti. Wanafunzi waliokumbushwa ndani ya siku 7 zilizopita wataruka.'), confirmText: SC.t('Send reminders', 'Tuma Vikumbusho'), danger: false, icon: 'fa-paper-plane' }))) return;
        const r = await SC.api.post('/fees/reminders'); SC.toast(r.sent ? SC.t(`${r.sent} fee reminder${r.sent === 1 ? '' : 's'} sent.`, `Vikumbusho ${r.sent} vimetumwa.`) : r.overdue ? SC.t('Everyone with overdue fees was already reminded this week.', 'Kila mtu mwenye ada zilizochelewa tayari amekumbushwa wiki hii.') : SC.t('No students have overdue fees. Nothing to send.', 'Hakuna wanafunzi wenye ada zilizochelewa. Hakuna cha kutuma.'));
      },
    });
    await draw();
    if (seg === 'receipt' && args[0]) { history.replaceState(null, '', '#fees'); SC.after(() => SC.receiptModal(args[0]).catch(SC.fail)); }
    if (args[0] === 'pay' && SC.can('fees.record')) { history.replaceState(null, '', '#fees'); SC.after(() => SC.payModal({ onDone: draw })); }
  };
})();
